name: Deploy HTTP Backend to dockerhub

on:
  push:
    branches:
        - main
    paths: 
        - 'apps/http-backend/**'
        - 'packages/**'
        - '.github/workflows/cd_backend.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - name: Docker login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./docker/http-backend.Dockerfile
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/whiteboard-http-backend:${{ github.sha }}
              ${{ secrets.DOCKERHUB_USERNAME }}/whiteboard-http-backend:latest
