name: Deploy Frontend to dockerhub

on:
  push:
    branches:
        - main
    paths:
        - 'apps/collaborative-board-frontend/**'
        - 'packages/**'
        - '.github/workflows/cd_frontend.yml'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: docker/frontend.Dockerfile
                push: true
                tags: |
                  ${{ secrets.DOCKERHUB_USERNAME }}/whiteboard-frontend:${{ github.sha }}
                  ${{ secrets.DOCKERHUB_USERNAME }}/whiteboard-frontend:latest
                  